// next-sitemap runs as a postbuild step and writes public/sitemap*.xml.
//
// Why additionalPaths + exclude:["*"] instead of the default crawler:
// next-sitemap was built for the Pages Router and does not reliably discover
// App Router routes that live under a dynamic [locale] segment. Rather than
// fight the crawler, we suppress its output (exclude everything) and emit a
// fully controlled set of locale-prefixed URLs ourselves, each carrying the
// correct per-path hreflang alternateRefs (+ x-default).
//
// The hreflang <link> tags in each page's <head> (generated by next-intl via
// generateMetadata) remain the primary signal for search engines; the sitemap
// reinforces it.

const siteUrl = "https://leonardoachaboiano.com";
const locales = ["en", "es", "de", "it"];
const defaultLocale = "en";

// Logical pages without a locale prefix. "" is the home page. Add new routes
// here as they are built.
const pages = [
  { path: "", priority: 1.0, changefreq: "monthly" },
  { path: "/cv", priority: 0.7, changefreq: "yearly" },
  { path: "/contact", priority: 0.5, changefreq: "yearly" },
];

function alternateRefs(pagePath) {
  // hrefIsAbsolute: true makes next-sitemap emit each href verbatim. Without it,
  // next-sitemap treats href as a language base origin and appends the current
  // page path, which collapses every alternate onto the same URL for subpath
  // (path-prefixed) locales.
  return [
    ...locales.map((locale) => ({
      href: `${siteUrl}/${locale}${pagePath}`,
      hreflang: locale,
      hrefIsAbsolute: true,
    })),
    {
      href: `${siteUrl}/${defaultLocale}${pagePath}`,
      hreflang: "x-default",
      hrefIsAbsolute: true,
    },
  ];
}

/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl,
  generateRobotsTxt: false, // robots handled by src/app/robots.ts
  exclude: ["*"],
  additionalPaths: async () => {
    const now = new Date().toISOString();
    return pages.flatMap((page) =>
      locales.map((locale) => ({
        loc: `${siteUrl}/${locale}${page.path}`,
        changefreq: page.changefreq,
        priority: page.priority,
        lastmod: now,
        alternateRefs: alternateRefs(page.path),
      })),
    );
  },
};
